apiVersion: v1
kind: Pod
metadata:
  name: test-thread
  namespace: test-thread
spec:
  restartPolicy: Never
  containers:
  - name: test-thread
    image: quay.io/dosman/test-thread
    command: ["/usr/local/bin/test-thread"]
    args: []
    imagePullPolicy: Always
    securityContext:
#     runAsUser: 0
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
        add: ["IPC_LOCK","NET_ADMIN","NET_BIND_SERVICE","SYS_NICE"]
