apiVersion: v1
kind: Pod
metadata:
  name: test-thread
  namespace: test-thread
spec:
# runtimeClassName: performance-openshift-node-performance-profile
  restartPolicy: Always
  containers:
  - name: test-thread
    image: quay.io/dosman/test-thread
#   command: ["sleep", "infinity"]
    args: []
    imagePullPolicy: Always #IfNotPresent #
    securityContext:
      runAsUser: 0
#     allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
        add: ["IPC_LOCK","NET_ADMIN","NET_BIND_SERVICE","SYS_NICE"]
